import 'package:eurohive/core/constants/app_assets.dart';

class Post {
  final String author;
  final String username;
  final String time;
  final String content;
  final String? imagePath;
  final String? profileImage; 
  int likes;
  int comments;
  int shares;
  bool isLiked;
  bool isShared;

  Post({
    required this.author,
    required this.username,
    required this.time,
    required this.content,
    this.imagePath,
     this.profileImage, 
    this.likes = 0,
    this.comments = 0,
    this.shares = 0,
    this.isLiked = false,
    this.isShared = false,
  });
}

final List<Post> demoPosts = [
  Post(
    author: 'Deivid Moura',
    username: '@deividvieiraz',
    time: '2h',
    content: 'Visitei a nova unidade hoje cedo. Impressiona ver como a expansão vai impactar não só a produção, mas também a geração de empregos na região.',
    imagePath: AppAssets.news1,
    profileImage: AppAssets.p1Foto,
    likes: 42,
    comments: 11,
    shares: 6,
  ),
  Post(
    author: 'João Marcelo',
    username: '@joaomarcelo',
    time: '5h',
    content: 'Orgulho de participar de um projeto que está reduzindo nosso impacto ambiental ao migrar parte da operação para energia renovável.',
    profileImage: AppAssets.p3Foto,
    likes: 33,
    comments: 5,
    shares: 3,
  ),
  Post(
    author: 'Vinicius Talhiaferro',
    username: '@vinivt',
    time: '1d',
    content: 'Nosso time apresentou os primeiros resultados de um estudo em doenças crônicas. Ainda é o começo, mas já mostra caminhos muito promissores.',
    imagePath: AppAssets.news3,
    profileImage: AppAssets.p12Foto,
    likes: 56,
    comments: 14,
    shares: 7,
  ),
  Post(
    author: 'Bruno Sena',
    username: '@bsena',
    time: '3d',
    content: 'Saiu o novo ranking internacional da saúde e estamos lá entre os destaques. Mérito de muita gente dedicada por aqui.',
    profileImage: AppAssets.p4Foto,
    likes: 44,
    comments: 9,
    shares: 5,
  ),
  Post(
    author: 'Mariana Costa',
    username: '@maricosta',
    time: '4d',
    content: 'Estive no novo centro de pesquisas ontem. A estrutura impressiona e deixa claro como a inovação está cada vez mais no centro do nosso trabalho.',
    profileImage: AppAssets.p2Foto,
    likes: 38,
    comments: 6,
    shares: 3,
  ),
  Post(
    author: 'Ricardo Alves',
    username: '@ralves',
    time: '5d',
    content: 'Concluir uma parceria que vai ampliar o acesso a medicamentos essenciais é daquelas coisas que fazem o esforço todo valer a pena.',
    profileImage: AppAssets.p11Foto,
    likes: 27,
    comments: 4,
    shares: 2,
  ),
  Post(
    author: 'Fernanda Lima',
    username: '@flima',
    time: '1w',
    content: 'Semana passada acompanhei uma ação social de atendimento médico em comunidades. É incrível ver de perto o impacto positivo que podemos gerar.',
    imagePath: AppAssets.news5,
    profileImage: AppAssets.p5Foto,
    likes: 61,
    comments: 18,
    shares: 9,
  ),
  Post(
    author: 'Lucas Pereira',
    username: '@lucpereira',
    time: '2w',
    content: 'A implementação de tecnologia 4.0 na linha de produção está sendo um aprendizado diário. Cada ajuste mostra como inovação e eficiência caminham juntas.',
    profileImage: AppAssets.p10Foto,
    likes: 34,
    comments: 7,
    shares: 3,
  ),
  Post(
    author: 'Carla Mendes',
    username: '@carlamendes',
    time: '3w',
    content: 'Hoje finalizamos mais uma turma do programa de qualificação de jovens. Ver a evolução deles em poucos meses é gratificante.',
    imagePath: AppAssets.news6,
    profileImage: AppAssets.p6Foto,
    likes: 48,
    comments: 12,
    shares: 6,
  ),
  Post(
    author: 'Paulo Henrique',
    username: '@paulohenrique',
    time: '1mo',
    content: 'Nosso laboratório recebeu certificação internacional de qualidade. Mais do que um selo, é reconhecimento do cuidado que colocamos em cada processo.',
    profileImage: AppAssets.p9Foto,
    likes: 53,
    comments: 10,
    shares: 6,
  ),
  Post(
    author: 'Juliana Rocha',
    username: '@jurocha',
    time: '1mo',
    content: 'Encerramos a campanha de vacinação deste ano. Foram milhares de pessoas atendidas — resultado de um esforço coletivo enorme.',
    imagePath: AppAssets.news2,
    profileImage: AppAssets.p7Foto,
    likes: 79,
    comments: 21,
    shares: 12,
  ),
  Post(
    author: 'André Santos',
    username: '@asantos',
    time: '2mo',
    content: 'Trabalhar com pesquisa clínica é saber lidar com expectativa e paciência. Hoje demos mais um passo com aprovação de novos medicamentos promissores.',
    profileImage: AppAssets.p1Foto,
    likes: 46,
    comments: 9,
    shares: 4,
  ),
  Post(
    author: 'Tatiane Moreira',
    username: '@tatimoreira',
    time: '2mo',
    content: 'Participei de uma conferência internacional sobre biotecnologia. Volto com a sensação de que estamos conectados às principais tendências do setor.',
    profileImage: AppAssets.p8Foto,
    likes: 32,
    comments: 8,
    shares: 3,
  ),
  Post(
    author: 'Gustavo Oliveira',
    username: '@gusoliveira',
    time: '3mo',
    content: 'Nova planta fabril agora opera com energia 100% limpa. É um marco importante no caminho da sustentabilidade.',
    profileImage: AppAssets.p10Foto,
    likes: 67,
    comments: 15,
    shares: 8,
  ),
  Post(
    author: 'Patrícia Souza',
    username: '@patisouza',
    time: '3mo',
    content: 'Já estão abertas as inscrições para o programa de estágio. Para quem está começando, é uma chance de ter experiência prática em várias áreas.',
    profileImage: AppAssets.p6Foto,
    likes: 58,
    comments: 19,
    shares: 7,
  ),
  Post(
    author: 'Rafael Martins',
    username: '@rafamartins',
    time: '4mo',
    content: 'Hoje foi meu primeiro dia no time de inovação. A recepção não poderia ter sido melhor. Ansioso pelos desafios que vêm pela frente.',
    profileImage: AppAssets.p2Foto,
    likes: 44,
    comments: 16,
    shares: 3,
  ),
  Post(
    author: 'Sofia Andrade',
    username: '@sofiaandrade',
    time: '4mo',
    content: 'Encerramos um hackathon interno ontem. Impressionante ver como, em poucas horas, ideias simples podem se transformar em protótipos viáveis.',
    profileImage: AppAssets.p7Foto,
    likes: 52,
    comments: 14,
    shares: 5,
  ),
  Post(
    author: 'Thiago Ramos',
    username: '@thiramos',
    time: '5mo',
    content: 'Um dos aprendizados mais valiosos deste semestre foi entender que inovação não acontece sozinha — ela depende de colaboração.',
    profileImage: AppAssets.p3Foto,
    likes: 37,
    comments: 9,
    shares: 4,
  ),
];
